// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scripts} from '../models';
import {data} from '../models';
import {main} from '../models';

export function CheckConnection():Promise<boolean>;

export function Close():Promise<void>;

export function DeleteScript(arg1:string):Promise<void>;

export function DisconnectPeer(arg1:string):Promise<void>;

export function Executor():Promise<scripts.ScriptExecutor>;

export function GetDataSources():Promise<Array<data.DataSource>>;

export function GetDividendData(arg1:string,arg2:string,arg3:string):Promise<Array<data.DividendData>>;

export function GetEODData(arg1:string,arg2:string,arg3:string):Promise<Array<data.EODData>>;

export function GetInsiderData(arg1:string,arg2:string,arg3:string):Promise<Array<data.InsiderTrade>>;

export function GetPeers():Promise<Array<main.Peer>>;

export function GetScriptContent(arg1:string):Promise<string>;

export function InstallScript(arg1:string):Promise<void>;

export function RequestData(arg1:string,arg2:data.DataRequest):Promise<void>;

export function ResetDataConnection():Promise<void>;

export function ResetDataProcessing():Promise<void>;

export function RetryConnection():Promise<void>;

export function RunScript(arg1:string):Promise<void>;

export function SearchData(arg1:data.DataRequest):Promise<Array<data.DataSource>>;

export function StopScript(arg1:string):Promise<void>;

export function UninstallScript(arg1:string):Promise<void>;

export function UploadScript(arg1:main.ScriptUploadData):Promise<void>;
