// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {data} from '../models';

export function CheckConnection():Promise<boolean>;

export function DeleteScript(arg1:string):Promise<void>;

export function GetActiveTransfers():Promise<Array<main.ActiveTransfer>>;

export function GetDataSources():Promise<Array<data.DataSource>>;

export function GetDividendData(arg1:string,arg2:string,arg3:string):Promise<Array<data.DividendData>>;

export function GetEODData(arg1:string,arg2:string,arg3:string):Promise<Array<data.EODData>>;

export function GetHealthDiagnostics():Promise<main.AppHealthDiagnostics>;

export function GetInsiderData(arg1:string,arg2:string,arg3:string):Promise<Array<data.InsiderTrade>>;

export function GetPeers():Promise<Array<data.Peer>>;

export function GetScriptContent(arg1:string):Promise<string>;

export function GetScripts():Promise<Array<main.ScriptInfo>>;

export function GetServerStatus():Promise<main.ServerStatus>;

export function GetSplitData(arg1:string,arg2:string,arg3:string):Promise<Array<data.SplitData>>;

export function InstallScript(arg1:string):Promise<void>;

export function RequestData(arg1:string,arg2:data.DataRequest):Promise<void>;

export function ResetDataConnection():Promise<void>;

export function ResetDataProcessing():Promise<void>;

export function RetryConnection():Promise<void>;

export function RunScript(arg1:string):Promise<void>;

export function SaveMarketData(arg1:data.MarketData):Promise<void>;

export function SearchData(arg1:data.DataRequest):Promise<Array<data.DataSource>>;

export function SearchMarketData(arg1:data.MarketDataFilter):Promise<Array<data.MarketData>>;

export function StopScript(arg1:string):Promise<void>;

export function UninstallScript(arg1:string):Promise<void>;

export function UpdateMarketData(arg1:Array<data.MarketData>):Promise<void>;

export function UploadMarketData(arg1:Record<string, any>):Promise<void>;

export function UploadScript(arg1:Record<string, string>):Promise<void>;
