// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';
import {main} from '../models';

export function CheckConnection():Promise<boolean>;

export function GetDataSources():Promise<Array<data.DataSource>>;

export function GetDividendData(arg1:string,arg2:string,arg3:string):Promise<Array<data.DividendData>>;

export function GetEODData(arg1:string,arg2:string,arg3:string):Promise<Array<data.EODData>>;

export function GetPeers():Promise<Array<data.Peer>>;

export function GetScriptContent(arg1:string):Promise<string>;

export function GetServerStatus():Promise<main.ServerStatus>;

export function RunScript(arg1:string):Promise<void>;

export function SaveMarketData(arg1:data.MarketData):Promise<void>;

export function SearchMarketData(arg1:data.MarketDataFilter):Promise<Array<data.MarketData>>;

export function StopScript(arg1:string):Promise<void>;
