// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckConnection() {
  return window['go']['main']['App']['CheckConnection']();
}

export function GetDataSources() {
  return window['go']['main']['App']['GetDataSources']();
}

export function GetDividendData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDividendData'](arg1, arg2, arg3);
}

export function GetEODData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetEODData'](arg1, arg2, arg3);
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function GetScriptContent(arg1) {
  return window['go']['main']['App']['GetScriptContent'](arg1);
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function RunScript(arg1) {
  return window['go']['main']['App']['RunScript'](arg1);
}

export function SaveMarketData(arg1) {
  return window['go']['main']['App']['SaveMarketData'](arg1);
}

export function SearchMarketData(arg1) {
  return window['go']['main']['App']['SearchMarketData'](arg1);
}

export function StopScript(arg1) {
  return window['go']['main']['App']['StopScript'](arg1);
}
